project:
  type: website

website:
  title: "ISSS624 - Geospatial Analytics App"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-on Exercise 1.1 - Geospatial Data Wrangling
            href: Hands-on_Ex1\Hands-on Ex1.qmd
          - text: Hands-on Exercise 1.2 - Choropleth Mapping with R
            href: Hands-on_Ex2\Hands-on Ex2.qmd
      - text: In class Exercises
        menu: 
          - text: In Class Exercise 1 - Applications of Spatial Weights
            href: In-Class_Ex1\In-class_Ex1.qmd
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

