project:
  type: website

website:
  title: "ISSS624 - Geospatial Analytics App"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-on Exercise Week 1.1 - Ch 1 Geospatial Data Wrangling
            href: Hands-on_Ex1\Hands-on Ex1.qmd
            
          - text: Hands-on Exercise Week 1.2 - Ch 2 Choropleth Mapping with R
            href: Hands-on_Ex2\Hands-on Ex2.qmd
            
          - text: Hands-on Exercise Week 2.1 - Ch 4 Global and Local Measures of Spatial Autocorrelation
            href: Hands-on_Ex3\Hands-on Ex3.qmd
            
          - text: Hands-on Exercise Week 3.1 - Ch 5 Geographical Segmentation with Spatially Constrained Clustering Techniques
            href: Hands-on_Ex4\Hands-on_Ex4.qmd
            
      - text: In class Exercises
        menu: 
          - text: In Class Exercise Week 1 - Ch 3 Applications of Spatial Weights
            href: In-Class_Ex1\In-class_Ex1.qmd
          - text: In Class Exercise Week 2 - Do functionally similar water points positively co-occur in Nigeria?
            href: In-Class_Ex2\In-class_Ex2.qmd
          - text: In Class Exercise Week 3 - 
            href: In-Class_Ex3\In-class_Ex3.qmd
            
      - text: Take Home Exercises    
        menu: 
          - text: Take Home Exercise 1 - Investigation of Water points in Nigeria
            href: Take-Home_Ex1\Take-Home_Ex1.qmd
          - text: Take Home Exercise 2 - Regionalization of Nigeria with Water points
            href: Take-Home_Ex2\Take-Home_Ex2.qmd
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

