project:
  type: website

website:
  page-navigation: true
  reader-mode: true
  page-footer: 
    left: "Copyright 2022, Allan Chong"
    
  title: "Applied Geospatial Analytics"
  navbar:
    left: 
      - text: Hands-On Exercises
        menu: 
          - text: Hands-on Exercise Week 1.1 - Ch 1 Geospatial Data Wrangling
            href: Hands-on_Ex1\Hands-on Ex1.qmd
            
          - text: Hands-on Exercise Week 1.2 - Ch 2 Choropleth Mapping with R
            href: Hands-on_Ex2\Hands-on Ex2.qmd
            
          - text: Hands-on Exercise Week 2.1 - Ch 4 Global and Local Measures of Spatial Autocorrelation
            href: Hands-on_Ex3\Hands-on Ex3.qmd
            
          - text: Hands-on Exercise Week 3.1 - Ch 5 Geographical Segmentation with Spatially Constrained Clustering Techniques
            href: Hands-on_Ex4\Hands-on_Ex4.qmd
            
          - text: Hands-on Exercise Week 4.1 - Ch 6 Calibrating Hedonic Pricing Model for Private High-rise Property with GWR Method
            href: Hands-on_Ex5\Hands-on_Ex5.qmd

      - text: In class Exercises
        menu: 
          - text: In Class Exercise Week 1 - Ch 3 Applications of Spatial Weights
            href: In-Class_Ex1\In-class_Ex1.qmd
            
          - text: In Class Exercise Week 2 - Do functionally similar water points positively co-occur in Nigeria?
            href: In-Class_Ex2\In-class_Ex2.qmd
            
          - text: In Class Exercise Week 3 - Spatially Constrained Clustering - ClustGeo Method
            href: https://mitb-isss624-ackw-gis-analytics.netlify.app/in-class_ex3/in-class_ex3#spatially-constrained-clustering---clustgeo-method
          
          - text: In Class Exercise Week 4 - Hedonic Pricing Models using GW model and Visualizing coefficient estimates of 2015 Condo Resale price in Singapore
            href: In-Class_Ex4\In-class_Ex4.qmd
          
          - text: In Class Exercise Week 5 - Investigation of functional and non functional water points using Geographical Weighted Logistic Regression (GWLR) in Nigeria
            href: In-Class_Ex5\In-class_Ex5.qmd  
      
      - text: Take Home Exercises    
        menu: 
          - text: Take Home Exercise 1 - Investigation of Water points in Nigeria
            href: Take-Home_Ex1\Take-Home_Ex1.qmd
            
          - text: Take Home Exercise 2 - Regionalization of Nigeria with Water points
            href: Take-Home_Ex2\Take-Home_Ex2.qmd
            
      - text: Course Website
        href: https://isss624-ay2022-23nov.netlify.app/ 
        
      - text: R for GDSA EBook
        href: https://r4gdsa.netlify.app/
            
    right:
      - href: https://github.com/allanckw
        icon: github
        aria-label: GitHub
      - href: index.qmd
        text: Home

format:
  html:
    theme: Cerulean
    css: styles.css
    toc: true

editor: visual

